In [1]:
import torch as t
t.Tensor(3, 4)

tensor([[1.3563e-19, 1.3563e-19, 4.5071e+16, 2.4756e-12],
        [4.1183e-11, 1.1704e-19, 1.3563e-19, 1.3563e-19],
        [4.5071e+16, 2.4756e-12, 4.1411e-11, 1.1704e-19]])

In [2]:
# 生成一个随机Tensor
x = t.rand(2, 3, 4)
x

tensor([[[0.2683, 0.1495, 0.9698, 0.5211],
         [0.8555, 0.4007, 0.6352, 0.3024],
         [0.4550, 0.2391, 0.5623, 0.3211]],

        [[0.0252, 0.3131, 0.9875, 0.1003],
         [0.0702, 0.2443, 0.2608, 0.8466],
         [0.4603, 0.7733, 0.1387, 0.1822]]])

In [3]:
# 查看x的形状
print(x.size())

print(x.size()[0], x.size()[1], x.size()[2])

torch.Size([2, 3, 4])
2 3 4


In [4]:
#两个Tensor相加
y = t.rand(2, 3, 4)
z = x + y
z

tensor([[[0.9847, 1.0203, 1.6382, 1.1281],
         [1.4748, 0.8412, 0.8719, 1.0463],
         [0.7840, 0.8364, 1.5326, 0.5811]],

        [[0.1999, 1.1234, 1.9369, 0.2544],
         [0.2200, 0.5460, 1.0673, 1.8135],
         [0.8517, 1.3583, 1.0541, 0.6716]]])

In [5]:
# 注意两个张量对应的维度要匹配
y1 = t.rand(3, 4, 2)
z1 = x + y1
z1

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 2

In [6]:
#通过函数add实现加法
print(t.add(x, y))

tensor([[[0.9847, 1.0203, 1.6382, 1.1281],
         [1.4748, 0.8412, 0.8719, 1.0463],
         [0.7840, 0.8364, 1.5326, 0.5811]],

        [[0.1999, 1.1234, 1.9369, 0.2544],
         [0.2200, 0.5460, 1.0673, 1.8135],
         [0.8517, 1.3583, 1.0541, 0.6716]]])


In [7]:
#另外一个写法，结果输出到提前定义好的Tensor中
result = t.Tensor(2, 3, 4)
t.add(x, y, out = result)
result

tensor([[[0.9847, 1.0203, 1.6382, 1.1281],
         [1.4748, 0.8412, 0.8719, 1.0463],
         [0.7840, 0.8364, 1.5326, 0.5811]],

        [[0.1999, 1.1234, 1.9369, 0.2544],
         [0.2200, 0.5460, 1.0673, 1.8135],
         [0.8517, 1.3583, 1.0541, 0.6716]]])

In [8]:
# 函数名带下划线 x.add_(y)会改变x，不带下划线x.add(y) 返回一个新的Tensor，x不改变
print(x)
x.add(y)
print(x)
x.add_(y)
print(x)

tensor([[[0.2683, 0.1495, 0.9698, 0.5211],
         [0.8555, 0.4007, 0.6352, 0.3024],
         [0.4550, 0.2391, 0.5623, 0.3211]],

        [[0.0252, 0.3131, 0.9875, 0.1003],
         [0.0702, 0.2443, 0.2608, 0.8466],
         [0.4603, 0.7733, 0.1387, 0.1822]]])
tensor([[[0.2683, 0.1495, 0.9698, 0.5211],
         [0.8555, 0.4007, 0.6352, 0.3024],
         [0.4550, 0.2391, 0.5623, 0.3211]],

        [[0.0252, 0.3131, 0.9875, 0.1003],
         [0.0702, 0.2443, 0.2608, 0.8466],
         [0.4603, 0.7733, 0.1387, 0.1822]]])
tensor([[[0.9847, 1.0203, 1.6382, 1.1281],
         [1.4748, 0.8412, 0.8719, 1.0463],
         [0.7840, 0.8364, 1.5326, 0.5811]],

        [[0.1999, 1.1234, 1.9369, 0.2544],
         [0.2200, 0.5460, 1.0673, 1.8135],
         [0.8517, 1.3583, 1.0541, 0.6716]]])


In [9]:
a =t.ones(2, 3)
b = 3.0 * t.ones(2, 3)
c = a - b
print(c)

tensor([[-2., -2., -2.],
        [-2., -2., -2.]])


In [10]:
d = t.ones(2,2)
e = a - d

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [11]:
a = t.Tensor([[1,2], [3,4], [5, 6]])
print(a)

#数乘矩阵
b = 2.0 * a
print(b)

#对应点相乘，sum后即为卷积
c = a * b
print(c)
print(c.sum())

# a: 3 * 2, b.t():2 * 3
# d: 3 * 3
d = a.mm(b.t())
print(d)


# a.t(): 2 * 3, b.t():3 * 2
# e: 2 * 2
e = a.t().mm(b)
print(e)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 2.,  4.],
        [ 6.,  8.],
        [10., 12.]])
tensor([[ 2.,  8.],
        [18., 32.],
        [50., 72.]])
tensor(182.)
tensor([[ 10.,  22.,  34.],
        [ 22.,  50.,  78.],
        [ 34.,  78., 122.]])
tensor([[ 70.,  88.],
        [ 88., 112.]])


In [12]:
a = t.Tensor([[1,2], [3,4], [5, 6]]) # 3 * 2
b = t.Tensor([[1, 2],[3,4],[5,6],[7,8]]) # 4 * 2

c = a.mm(b.t()) # 3 * 4 
print(c)


#如果矩阵大小不满足 x: i * n, y:n * j的方式，则出错
c = a.mm(b)

tensor([[ 5., 11., 17., 23.],
        [11., 25., 39., 53.],
        [17., 39., 61., 83.]])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 4x2)

In [13]:
#A: 3 * 2
#x: 1 * 2
A = t.Tensor([[1,2], [3,4], [5, 6]]) 
x = t.Tensor([[1, 2]])
print(A)
print(x)

# A: 3*2; b.t(): 2 * 1
# 结果：3 * 1
c = A.mm(x.t())
print(c)

#x: 1 * 2, A.t(): 2 * 3
# 结果: 1 * 3
d = x.mm(A.t())
print(d)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 2.]])
tensor([[ 5.],
        [11.],
        [17.]])
tensor([[ 5., 11., 17.]])


In [14]:
import torch as t
a=t.Tensor([[[1,2,3],[4,5,6]]])
b=t.Tensor([1,2,3,4,5,6])

print(a.view(1,6))
print(b.view(1,6))

tensor([[1., 2., 3., 4., 5., 6.]])
tensor([[1., 2., 3., 4., 5., 6.]])


In [15]:
a=t.Tensor([[[1,2,3, 4],[5,6,7,8]]])
print(a)
print('---------------------------------')
print(a.view(4,2))
print('---------------------------------')
print(a.view(2, 2 ,2))
print('---------------------------------')

tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])
---------------------------------
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
---------------------------------
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
---------------------------------


In [17]:
# Tensor的选取操作与numpy类似
x = t.rand(2, 3, 4)

print(x)
x[0, 0, :]

tensor([[[0.8445, 0.8684, 0.2850, 0.7711],
         [0.1709, 0.6919, 0.9432, 0.8347],
         [0.0158, 0.4547, 0.9059, 0.6666]],

        [[0.2744, 0.8219, 0.0331, 0.1305],
         [0.8894, 0.8079, 0.1059, 0.3543],
         [0.7605, 0.5903, 0.2350, 0.2651]]])


tensor([0.8445, 0.8684, 0.2850, 0.7711])

In [18]:
x[:, 0, 0] 

tensor([0.8445, 0.2744])

In [19]:
x[:, :, 0]

tensor([[0.8445, 0.1709, 0.0158],
        [0.2744, 0.8894, 0.7605]])

In [20]:
x[:,1:3, 2:4]

tensor([[[0.9432, 0.8347],
         [0.9059, 0.6666]],

        [[0.1059, 0.3543],
         [0.2350, 0.2651]]])

In [21]:
#PyTorch Tensor与Numpy之间的转换
#tensor->numpy
a = t.ones(2, 3, 4)
b = a.numpy()
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [22]:
# numpy --> Tensor
import numpy as np
a = np.ones(5)
b = t.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [23]:
# 上述转换中，Tensor和Numpy共享内容，所以修改一个另一个也随之改变

print(a)
b.add_(1) #注意是下划线add_
print(a)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]


In [24]:
#支持GPU，将x和y都转移到GPU中进行运算
# 在大规模数据复杂Tensor运算时，具有优势；
# 小规模数据时由于具有数据转移开销，CPU会更快一点

#本机器不支持GPU，不会运行以下代码
if t.cuda.is_available():
    x = x.cuda() #将张量x转移到GPU中
    y = y.cuda() #将张量y转移到GPU中
    z = x + y #在GPU中运算x + y
else:
    z = x + y
print(z)

tensor([[[1.5609, 1.7392, 0.9534, 1.3781],
         [0.7902, 1.1324, 1.1799, 1.5786],
         [0.3449, 1.0520, 1.8761, 0.9267]],

        [[0.4491, 1.6322, 0.9825, 0.2846],
         [1.0392, 1.1096, 0.9125, 1.3212],
         [1.1519, 1.1753, 1.1504, 0.7545]]], device='cuda:0')


In [25]:
#如果不进行判断，x.cuda()语句在没有GPU环境的情况下出错
x = x.cuda() #将张量x转移到GPU中
y = y.cuda() #将张量y转移到GPU中
x + y #在GPU中运算x + y

tensor([[[1.5609, 1.7392, 0.9534, 1.3781],
         [0.7902, 1.1324, 1.1799, 1.5786],
         [0.3449, 1.0520, 1.8761, 0.9267]],

        [[0.4491, 1.6322, 0.9825, 0.2846],
         [1.0392, 1.1096, 0.9125, 1.3212],
         [1.1519, 1.1753, 1.1504, 0.7545]]], device='cuda:0')

In [26]:
# 求函数 y= x^2 在x=3时的导数: y'(3) = dy/dx|x=3

x=t.tensor(3.0,requires_grad=True)
y=x.mul(x)

#判断x,y是否是可以求导的
print(x.requires_grad)
print(y.requires_grad)

#求导，通过backward函数来实现
y.backward()

#查看导数，也即所谓的梯度
print(x.grad)

True
True
tensor(6.)


In [27]:
# 练习
# 求y = max(0, x)在x=1和x=-1处的导数


#定义x=1.0 和y=max(0, x)
x = t.tensor(1.0, requires_grad=True)
y = t.max(x, t.zeros(1,1))

#调用backward并打印导数
y.backward()
print(x.grad)

# 改变x后需要重新执行y和backward
x = t.tensor(-1.0, requires_grad=True)
y = t.max(x, t.zeros(1,1))
y.backward()
print(x.grad)

tensor(1.)
tensor(0.)


In [29]:
# 求y = 1/x
x = t.tensor(0.5, requires_grad=True)
y = t.reciprocal(x)
y.backward()
print(x.grad)

x = t.tensor(1.0, requires_grad=True)
y = t.reciprocal(x)
y.backward()
print(x.grad)

x = t.tensor(2., requires_grad=True)
y = t.reciprocal(x)
y.backward()
print(x.grad)



tensor(-4.)
tensor(-1.)
tensor(-0.2500)


In [30]:
# 求y = 1/\sqrt(x)
x = t.tensor(0.5, requires_grad=True)
y = t.reciprocal( t.sqrt(x))
y.backward()
print(x.grad)

x = t.tensor(1.0, requires_grad=True)
y = t.reciprocal( t.sqrt(x))
y.backward()
print(x.grad)

x = t.tensor(2.0, requires_grad=True)
y = t.reciprocal( t.sqrt(x))
y.backward()
print(x.grad)

tensor(-1.4142)
tensor(-0.5000)
tensor(-0.1768)


In [31]:
# 求y = 1/\sqrt(x)
x = t.tensor(1.0, requires_grad=True)
g = t.sqrt(x)
y = t.reciprocal(g)

g.backward(retain_graph=True)
print(x.grad)


y.backward(retain_graph=True)
print(x.grad)


tensor(0.5000)
tensor(0.)


In [32]:
# f(x,y) = x^2 + 2 * y^2 + xy
# 在 (1.0, 1.0)处的导数
x = t.tensor(1.0, requires_grad=True)
y = t.tensor(1.0, requires_grad=True)

f = x.pow(2) + t.tensor(2.0).mul(y.pow(2)) + x.mul(y)
f.backward()
print(x.grad)
print(y.grad)

tensor(3.)
tensor(5.)


In [33]:
# f(x,y, z) = ln(e^x + e^y + e^z)
# 在 (0.0, 2.0, 5.0)处的导数
x = t.tensor(0.0, requires_grad=True)
y = t.tensor(2.0, requires_grad=True)
z = t.tensor(5.0, requires_grad=True)

f = t.log(t.exp(x) + t.exp(y) + t.exp(z))
f.backward()
print(x.grad)
print(y.grad)
print(z.grad)

tensor(0.0064)
tensor(0.0471)
tensor(0.9465)


In [34]:
# 注意：把x和b定义为一个1*2的矩阵，x.mm()是矩阵乘法
x = t.tensor([[1.0, 2.0]], requires_grad=True)

A = t.tensor([[1.0, 1.0], 
              [1.0, 2.0]])
b = t.tensor([[1.0, 0.0]])
print(x, A, b)
print()

f = x.mm(A).mm(x.t()) + x.mm(b.t())
print(f)
print()
f.backward()
print(x.grad)

tensor([[1., 2.]], requires_grad=True) tensor([[1., 1.],
        [1., 2.]]) tensor([[1., 0.]])

tensor([[14.]], grad_fn=<AddBackward0>)

tensor([[ 7., 10.]])


In [35]:
# 注意：把x和b定义为一个1*2的矩阵，x.mm()是矩阵乘法
x = t.tensor([[1.0, 2.0]], requires_grad=True)
y = t.tensor([[3.0, 4.0]], requires_grad=True)

A = t.tensor([[1.0, 1.0], 
              [1.0, 2.0]])
b = t.tensor([[1.0, 0.0]])
print(x, y, A, b)
print()

f = x.mm(A).mm(y.t()) + x.mm(b.t())
print(f)
print()
f.backward()
print(x.grad)
print(y.grad)

tensor([[1., 2.]], requires_grad=True) tensor([[3., 4.]], requires_grad=True) tensor([[1., 1.],
        [1., 2.]]) tensor([[1., 0.]])

tensor([[30.]], grad_fn=<AddBackward0>)

tensor([[ 8., 11.]])
tensor([[3., 5.]])


In [36]:
# f(A) = x A A^T y 
x = t.tensor([[1.0, 2.0]])
y = t.tensor([[3.0, 4.0]])

A = t.tensor([[2.0, 12.0], 
              [1.0, 2.0]], requires_grad=True)
b = t.tensor([[1.0, 0.0]])
print(x, y, A, b)
print()

f = x.mm(A).mm(y.t()) + x.mm(b.t())
print(f)
print()
f.backward()
#print(x.grad)
#print(y.grad)
print(A.grad)

tensor([[1., 2.]]) tensor([[3., 4.]]) tensor([[ 2., 12.],
        [ 1.,  2.]], requires_grad=True) tensor([[1., 0.]])

tensor([[77.]], grad_fn=<AddBackward0>)

tensor([[3., 4.],
        [6., 8.]])
