In [1]:
import torch
import torch.nn as nn
import numpy as np
from PIL import Image
from torchvision import transforms
import torch.nn.functional as F

In [2]:
image = Image.open('5.jpg').convert('RGB')
input = transforms.ToTensor()(image).unsqueeze(0)
print(input.shape)
#Conv-1
Conv1 = nn.Conv2d(in_channels=3, out_channels=6, kernel_size=5, stride=1, padding=0)
Nf1 = nn.ReLU()
output1 = Nf1(Conv1(input))
print(output1.shape)

torch.Size([1, 3, 32, 32])
torch.Size([1, 6, 28, 28])


In [3]:
#Poo1-1
Pool1 = nn.MaxPool2d((2,2), stride=2, padding=0)
output1 = Pool1(output1)
print(output1.shape)

torch.Size([1, 6, 14, 14])


In [5]:
#pool - test
x = torch.tensor(
    [[3, 3, 2, 1, 0], 
     [0, 0, 1, 3, 1], 
     [3, 1, 2, 2, 3], 
     [2, 0, 0, 2, 2], 
     [2, 0, 0, 0, 1]], dtype=torch.float64)
x = x.view(1, 5, 5)
MP = nn.MaxPool2d(kernel_size= 3, stride=1)
y = MP(x)
print(y)

MP2 = nn.AvgPool2d(kernel_size= 3, stride=1)
y = MP2(x)
print(y)

tensor([[[3., 3., 3.],
         [3., 3., 3.],
         [3., 2., 3.]]], dtype=torch.float64)
tensor([[[1.6667, 1.6667, 1.6667],
         [1.0000, 1.2222, 1.7778],
         [1.1111, 0.7778, 1.3333]]], dtype=torch.float64)


In [6]:
#pool test2
a = torch.randn(3,5,10)
MP3 = nn.MaxPool2d((5,1))
c = MP3(a)
print(c.shape)

x = torch.rand(1, 3, 7, 7)
MP4 = nn.AvgPool2d(kernel_size=2, stride=2)
print(MP4.forward(x).shape)

torch.Size([3, 1, 10])
torch.Size([1, 3, 3, 3])


In [7]:
#Conv-2
Conv2 = nn.Conv2d(in_channels=6, out_channels=16, kernel_size=5, stride=1, padding=0)
Nf2 = nn.ReLU()
output2 = Nf2(Conv2(output1))
print(output2.shape)

torch.Size([1, 16, 10, 10])


In [8]:
#Poo1-2
Pool2 = nn.MaxPool2d((2,2), stride=2, padding=0)
output2 = Pool1(output2)
print(output2.shape)

torch.Size([1, 16, 5, 5])


In [9]:
#Flatten
output3 = output2.flatten(1)
print(output3.shape)

#FC
FC = nn.Linear(400,10)
output3 = FC(output3)
print(output3.shape)

#SoftMax
output = torch.softmax(output3, dim=1)
print(output)

torch.Size([1, 400])
torch.Size([1, 10])
tensor([[0.1090, 0.1111, 0.1067, 0.0894, 0.0909, 0.0953, 0.0969, 0.0911, 0.1015,
         0.1082]], grad_fn=<SoftmaxBackward0>)


In [10]:
# A class implementation
class CNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=3,out_channels=6,kernel_size=5,stride=1,padding=0)
        self.pool1 = nn.MaxPool2d((2,2),stride=2,padding=0)
        self.conv2 = nn.Conv2d(in_channels=6,out_channels=16,kernel_size=5,stride=1,padding=0)
        self.pool2 = nn.MaxPool2d((2,2),stride=2,padding=0)
        self.fc = nn.Linear(400,10)
        self.nf = nn.ReLU()

    def forward(self, x):
        output1 = self.nf(self.conv1(x))
        print(output1.shape)
        output1 = self.pool1(output1)
        print(output1.shape)
        output2 = self.nf(self.conv2(output1))
        print(output2.shape)
        output2 = self.pool2(output2)
        print(output2.shape)
        # Flatten
        output3 = output2.flatten(1)
        print(output3.shape)
        # FC
        output3 = self.fc(output3)
        print(output3.shape)
        # SoftMax
        output = torch.softmax(output3,dim=1)
        return output

image = Image.open('5.jpg').convert('RGB')
input = transforms.ToTensor()(image).unsqueeze(0)
print(input.shape)

model = CNN()
output = model(input)
print(output)

torch.Size([1, 3, 32, 32])
torch.Size([1, 6, 28, 28])
torch.Size([1, 6, 14, 14])
torch.Size([1, 16, 10, 10])
torch.Size([1, 16, 5, 5])
torch.Size([1, 400])
torch.Size([1, 10])
tensor([[0.1148, 0.0802, 0.0902, 0.0974, 0.0964, 0.1136, 0.1079, 0.1117, 0.0898,
         0.0981]], grad_fn=<SoftmaxBackward0>)


In [11]:
image1 = Image.open('5.jpg').convert('RGB')
input1 = transforms.ToTensor()(image).unsqueeze(0)
image2 = Image.open('3.jpg').convert('RGB')
input2 = transforms.ToTensor()(image).unsqueeze(0)
input = torch.cat([input1, input2], 0)
print(input.shape)

model = CNN()
output = model(input)
print(output)

torch.Size([2, 3, 32, 32])
torch.Size([2, 6, 28, 28])
torch.Size([2, 6, 14, 14])
torch.Size([2, 16, 10, 10])
torch.Size([2, 16, 5, 5])
torch.Size([2, 400])
torch.Size([2, 10])
tensor([[0.1036, 0.0995, 0.0887, 0.0912, 0.0944, 0.0996, 0.0997, 0.1055, 0.1075,
         0.1102],
        [0.1036, 0.0995, 0.0887, 0.0912, 0.0944, 0.0996, 0.0997, 0.1055, 0.1075,
         0.1102]], grad_fn=<SoftmaxBackward0>)
